//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketBooking.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        public Booking()
        {
            this.SeatBookings = new HashSet<SeatBooking>();
        }
    
        public int BookingId { get; set; }

        [Display(Name = "User Name")]
        public int UserId { get; set; }

        [Display(Name = "Show Time")]
        public int ShowId { get; set; }

        [Display(Name = "Movie Name")]
        public int MovieId { get; set; }
    
        public virtual Show Show { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<SeatBooking> SeatBookings { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
