//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace MovieTicketBooking.Models
{
    public partial class MovieShow
    {
        [Display(Name = "Show Time")]
        public int ShowId { get; set; }

        [Display(Name = "Movie Name")]
        public int MovieId { get; set; }
        public int MovieShowId { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual Show Show { get; set; }
    }
}
