//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketBooking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieTicketContext : DbContext
    {
        public MovieTicketContext()
            : base("name=MovieTicketContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<MovieShow> MovieShows { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Screen> Screens { get; set; }
        public virtual DbSet<SeatBooking> SeatBookings { get; set; }
        public virtual DbSet<Seat> Seats { get; set; }
        public virtual DbSet<Show> Shows { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
