//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketBooking.Models
{
    using System.Collections.Generic;

    public partial class Screen
    {
        public Screen()
        {
            this.Shows = new HashSet<Show>();
            this.Seats = new HashSet<Seat>();
        }
    
        public int ScreenId { get; set; }
        public int ScreenNo { get; set; }
    
        public virtual ICollection<Show> Shows { get; set; }
        public virtual ICollection<Seat> Seats { get; set; }
    }
}
