//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatBooking
    {
        public int BookingId { get; set; }
        public int SeatId { get; set; }
        public int SeatBookingId { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
